name: Cypress Docker Test Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  cypress_tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t cypress_automation .

      - name: Run Cypress tests in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -v /app/node_modules \
            cypress_automation

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber-htmlreport/
